# TENSOR


Pytorch에서는 Tensor를 사용하여 모델의 input과 ouput, 모델의 parameter들을 encode(부호화)

* 텐서는 GPU나 다른 하드웨어 가속기에서 실행
* Numpy의 ndarray와 유사
* 텐서와 Numpy array는 동일한 내부 메모리를 공유할 수 있어 데이터를 복사할 필요가 없음.
* 텐서는 Automatic differentiation에 최적화

In [1]:
import torch
import numpy as np

## 텐서 초기화

* 데이터로부터 직접 텐서 생성

In [2]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

* Numpy 배열로부터 생성하기

In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


* 다른 텐서루부터 생성하기

명시적으로 override 하지 않으면, 인자로 주어진 텐서의 shape, dadtatype을 유지함

In [4]:
x_ones = torch.ones_like(x_data) # x_data의 속성 유지
print(f"Ones Tensor: \n {x_ones}\n") 

x_rand = torch.rand_like(x_data, dtype=torch.float) # x_data의 속성을 덮어씀
print(f'Random Tensor : \n {x_rand} \n')

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]])

Random Tensor : 
 tensor([[0.3293, 0.4096],
        [0.2634, 0.1073]]) 



* random 또는 constant 값을 사용하기

shape은 텐서의 차원을 나타내는 tuple, 출력 텐서의 차원을 결정

In [5]:
shape = (2, 3, )
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f'Random Tensor: \n {rand_tensor} \n')
print(f'Ones Tensor: \n {ones_tensor} \n')
print(f'Zeros Tensor: \n {zeros_tensor}')

Random Tensor: 
 tensor([[0.0996, 0.3233, 0.5442],
        [0.3027, 0.4420, 0.1108]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


## 텐서의 속성(Attribute)
텐서의 shape, datatype, 어느 장치에 저장되는지를 나타냄

In [6]:
tensor = torch.rand(3, 4)

print(f'Shape of tensor : {tensor.shape}')
print(f'Datatype of tensor : {tensor.dtype}')
print(f'Device tensor is stored on: {tensor.device}')

Shape of tensor : torch.Size([3, 4])
Datatype of tensor : torch.float32
Device tensor is stored on: cpu


## 텐서 연산(Operation)

* transposing, indexing, slicing, 수학계산, 선형대수, random sampling 등 100가지 이상의 텐서연산이 있음
* 각 연산들은 GPU에서 실행할 ㅅ ㅜ있음
* 기본적으로 텐서는 CPU에 생성, .to 메소드를 사용하여 GPU로 텐서를 명시적으로 이동할수 있음.

In [7]:
# GPU가 존재하면 텐서를 이동함
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

* NumPy식 표준 인덱싱과 슬라이싱

In [8]:
tensor = torch.ones(4, 4)

print(f'First row: {tensor[0]}')
print(f'First column : {tensor[:, 0]}')
print(f'Last column : {tensor[..., -1]}')

tensor[:, 1]= 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column : tensor([1., 1., 1., 1.])
Last column : tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


* 텐서 합치기 : torch.cat을 사용하여 주어진 차원에 따라 일련의 텐서를 연결할 수 있음.


In [9]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [10]:
t2 = torch.cat([tensor, tensor, tensor], dim=0)
print(t2)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


* 산술연산(Arithmetic operations)

In [11]:
# 두 텐서간의 matrix multiplication을 계산, y1, y2, y3는 모두 같은 값
# ''tensor.T''는 텐서간의 transpose를 반환

y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [12]:
# element-wise product를 계산, z1, z2, z3는 모두 같은값
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

* Single-element 텐서 : 텐서의 모든 값을 하나로 aggregate하여 요소가 하나의 텐서인 경우, item()을 사용하여 Python 숫자값으로 변환할 수 있음.

In [13]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


* 바꿔치기(in-place) 연산

연산 결과를 피연산자(operand)에 저장하는 연산, _ 접미사를 가짐
x.copy_(y)나 x.t_는 x를 변경함

In [14]:
print(f'{tensor} \n')
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


## NumPy 변환(Bridge)

CPU상의 텐서와 Numpy 배열은 메모리 공간을 공유, 하나를 변경하면 다른 하나도 변경됨.


* 텐서를 NumPy array로 변환하기

In [15]:
t = torch.ones(5)
print(f't: {t}')

n = t.numpy()
print(f"n : {n}")

t: tensor([1., 1., 1., 1., 1.])
n : [1. 1. 1. 1. 1.]


텐서의 변경사항이 NumPy 배열에 반영됨.

In [16]:
t.add_(1)
print(f't:{t}')
print(f"n:{n}")

t:tensor([2., 2., 2., 2., 2.])
n:[2. 2. 2. 2. 2.]


* NumPy 배열을 텐서로 변환하기

In [17]:
n = np.ones(5)
t = torch.from_numpy(n)


In [18]:
# numpy 배열의 변경사항이 텐서에 반영
np.add(n, 1, out=n)
print(f"t : {t}")
print(f"n: {n}")

t : tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
