# Pytorch Tensor

In [2]:
import torch
import math

In [3]:
x = torch.empty(3, 4)
print(type(x))
print(x)

<class 'torch.Tensor'>
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


* 1차원 tensor는 vector
* 2차원 tensor는 matrix
* 2차원보다 큰 차원을 가진 것들은 그냥 tensor

In [4]:
zeros = torch.zeros(2, 3)
print(zeros)

ones = torch.ones(2, 3)
print(ones)

torch.manual_seed(1729)
random = torch.rand(2, 3)
print(random)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


In [5]:
torch.manual_seed(1729) # 연구환경에서 연구 결과의 재현 가능성에 대한 확신을 얻고 싶을 때 모델의 학습 가중치와 같은 무작위 값을 가진 tensor로 초기화하는 것
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)

torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random3)

random4 = torch.rand(2, 3)
print(random4)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


## Tensor의 shape

두개 이상의 tensor에 대한 연산을 수행할 때, tensor들은 같은 shape를 필요로함.
차원의 개수가 같아야 하고, 각 차원마다 원소 수가 같아야한다.
torch.*_like() 함수 사용

In [6]:
x = torch.empty(2, 2, 3)
print(x.shape)
print(x)

empty_like_x = torch.empty_like(x)
print(empty_like_x.shape)
print(empty_like_x)

zeros_like_x = torch.zeros_like(x)
print(zeros_like_x.shape)
print(zeros_like_x)

ones_like_x = torch.ones_like(x)
print(ones_like_x.shape)
print(ones_like_x)

rand_like_x = torch.rand_like(x)
print(rand_like_x.shape)
print(rand_like_x)

torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])
torch.Size([2, 2, 3])
tensor([[[0.6128, 0.1519, 0.0453],
         [0.5035, 0.9978, 0.3884]],

        [[0.6929, 0.1703, 0.1384],
         [0.4759, 0.7481, 0.0361]]])


In [7]:
# 텐서생성, Pytorch Collection 형식의 데이터를 직접적으로 명시

some_constants = torch.tensor([[3.1415926, 2.71828], [1.61803, 0.0072897]])
print(some_constants)

some_integers = torch.tensor((2, 3, 5, 7, 11, 13, 17, 19))
print(some_integers)

more_integers = torch.tensor(((2, 4, 6), [3, 6, 9]))
print(more_integers)

# torch.tensor()로 이미 튜플이나 리스트 형태로 이루어진 데이터를 가지고 있는 경우
# 중첩된 형태의 collection 자료형은 다차원 텐서로

tensor([[3.1416, 2.7183],
        [1.6180, 0.0073]])
tensor([ 2,  3,  5,  7, 11, 13, 17, 19])
tensor([[2, 4, 6],
        [3, 6, 9]])


In [8]:
some_constants.shape


torch.Size([2, 2])

In [9]:
some_integers.shape

torch.Size([8])

In [10]:
more_integers.shape

torch.Size([2, 3])

In [11]:
a = torch.ones((2, 3), dtype=torch.int16)
print(a)

b = torch.rand((2, 3), dtype=torch.float64) * 20.
print(b)

c = b.to(torch.int32)
print(c)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[ 0.9956,  1.4148,  5.8364],
        [11.2406, 11.2083, 11.6692]], dtype=torch.float64)
tensor([[ 0,  1,  5],
        [11, 11, 11]], dtype=torch.int32)


In [12]:
ones = torch.zeros(2, 2) + 1
twos = torch.ones(2, 2) * 2
threes = (torch.ones(2, 2) * 7 - 1) / 2
fours = twos ** 2
sqrt2s = twos ** 0.5

print(ones)
print(twos)
print(threes)
print(fours)
print(sqrt2s)

tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[4., 4.],
        [4., 4.]])
tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])


In [13]:
powers2 = twos ** torch.tensor([[1, 2], [3, 4]])
print(powers2)

fives = ones + fours
print(fives)

dozens = threes * fours
print(dozens)

tensor([[ 2.,  4.],
        [ 8., 16.]])
tensor([[5., 5.],
        [5., 5.]])
tensor([[12., 12.],
        [12., 12.]])


## Tensor Broadcasting

텐서는 같은 shape 끼리만 연산이 가능하다는 규칙의 예외가 tensor broadcasting

In [14]:
rand = torch.rand(2, 4)
doubled = rand * (torch.ones(1, 4) * 2)

print(rand)
print(doubled)

tensor([[0.6146, 0.5999, 0.5013, 0.9397],
        [0.8656, 0.5207, 0.6865, 0.3614]])
tensor([[1.2291, 1.1998, 1.0026, 1.8793],
        [1.7312, 1.0413, 1.3730, 0.7228]])


In [15]:
a =     torch.ones(4, 3, 2)

b = a * torch.rand(   3, 2) # 세번째와 두번째 차원이 a랑 동일하고, 첫번째 차원은 존재하지 않습니다.
print(b)

c = a * torch.rand(   3, 1) # 세번째 차원 = 1이고, 두번째 차원은 a랑 동일합니다.
print(c)

d = a * torch.rand(   1, 2) # 세번째 차원이 a랑 동일하고, 두번째 차원 = 1입니다.
print(d)

tensor([[[0.6493, 0.2633],
         [0.4762, 0.0548],
         [0.2024, 0.5731]],

        [[0.6493, 0.2633],
         [0.4762, 0.0548],
         [0.2024, 0.5731]],

        [[0.6493, 0.2633],
         [0.4762, 0.0548],
         [0.2024, 0.5731]],

        [[0.6493, 0.2633],
         [0.4762, 0.0548],
         [0.2024, 0.5731]]])
tensor([[[0.7191, 0.7191],
         [0.4067, 0.4067],
         [0.7301, 0.7301]],

        [[0.7191, 0.7191],
         [0.4067, 0.4067],
         [0.7301, 0.7301]],

        [[0.7191, 0.7191],
         [0.4067, 0.4067],
         [0.7301, 0.7301]],

        [[0.7191, 0.7191],
         [0.4067, 0.4067],
         [0.7301, 0.7301]]])
tensor([[[0.6276, 0.7357],
         [0.6276, 0.7357],
         [0.6276, 0.7357]],

        [[0.6276, 0.7357],
         [0.6276, 0.7357],
         [0.6276, 0.7357]],

        [[0.6276, 0.7357],
         [0.6276, 0.7357],
         [0.6276, 0.7357]],

        [[0.6276, 0.7357],
         [0.6276, 0.7357],
         [0.6276, 0.7357]]])


* Pytorch의 broadcasting : 다른 크기의 텐서간에 연산을 수행할 수 있게 해주는 기능
broadcasting을 통해 크기가 다른 텐서간의 연산을 자동으로 확장하여 일치시킴.

1. 모양이 다를 경우 : 각 차언에서 두 텐서 모양이 다르면 더 작은 모양의 텐서가 더 큰 모양의 텐서와 동일한 모양을 가지도록 확장됨.

2. 뒤쪽 차원부터 비교

3. 크기가 1인 차원 : 차원의 크기가 1인 경우 해당 차원은 다른 텐서의 해당 차원과 일치하도록 확장됨.

In [16]:
# 공용 함수
a = torch.rand(2, 4) * 2 - 1
print('Common functions:')
print(torch.abs(a))
print(torch.ceil(a))
print(torch.floor(a))
print(torch.clamp(a, -0.5, 0.5))

# 삼각 함수와 그 역함수들
angles = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
sines = torch.sin(angles)
inverses = torch.asin(sines)
print('\nSine and arcsine:')
print(angles)
print(sines)
print(inverses)

# 비트 연산
print('\nBitwise XOR:')
b = torch.tensor([1, 5, 11])
c = torch.tensor([2, 7, 10])
print(torch.bitwise_xor(b, c))

# 비교 연산:
print('\nBroadcasted, element-wise equality comparison:')
d = torch.tensor([[1., 2.], [3., 4.]])
e = torch.ones(1, 2)  # 많은 비교 연산자들은 broadcasting을 지원합니다!
print(torch.eq(d, e)) # bool 자료형을 가진 tensor를 반환합니다.

# 차원 감소 연산:
print('\nReduction ops:')
print(torch.max(d))        # 단일 원소 tensor를 반환합니다.
print(torch.max(d).item()) # 반환한 tensor로부터 값을 추출합니다.
print(torch.mean(d))       # 평균
print(torch.std(d))        # 표준 편차
print(torch.prod(d))       # 모든 숫자의 곱
print(torch.unique(torch.tensor([1, 2, 1, 2, 1, 2]))) # 중복되지 않은 값들을 걸러냅니다.

# 벡터와 선형 대수 연산
v1 = torch.tensor([1., 0., 0.])         # x축 단위 벡터
v2 = torch.tensor([0., 1., 0.])         # y축 단위 벡터
m1 = torch.rand(2, 2)                   # 무작위 행렬
m2 = torch.tensor([[3., 0.], [0., 3.]]) # 단위 행렬에 3을 곱한 결과

print('\nVectors & Matrices:')
print(torch.cross(v2, v1)) # z축 단위 벡터의 음수값 (v1 x v2 == -v2 x v1)
print(m1)
m3 = torch.matmul(m1, m2)
print(m3)                  # m1 행렬을 3번 곱한 결과
print(torch.svd(m3))       # 특이값 분해

Common functions:
tensor([[0.9238, 0.5724, 0.0791, 0.2629],
        [0.1986, 0.4439, 0.6434, 0.4776]])
tensor([[-0., -0., 1., -0.],
        [-0., 1., 1., -0.]])
tensor([[-1., -1.,  0., -1.],
        [-1.,  0.,  0., -1.]])
tensor([[-0.5000, -0.5000,  0.0791, -0.2629],
        [-0.1986,  0.4439,  0.5000, -0.4776]])

Sine and arcsine:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 0.7854])

Bitwise XOR:
tensor([3, 2, 1])

Broadcasted, element-wise equality comparison:
tensor([[ True, False],
        [False, False]])

Reduction ops:
tensor(4.)
4.0
tensor(2.5000)
tensor(1.2910)
tensor(24.)
tensor([1, 2])

Vectors & Matrices:
tensor([ 0.,  0., -1.])
tensor([[0.7375, 0.8328],
        [0.8444, 0.2941]])
tensor([[2.2125, 2.4985],
        [2.5332, 0.8822]])
torch.return_types.svd(
U=tensor([[-0.7889, -0.6145],
        [-0.6145,  0.7889]]),
S=tensor([4.1498, 1.0548]),
V=tensor([[-0.7957,  0.6056],
        [-0.6056, -0.7957]]))


C:\Users\HeawonJeong\AppData\Local\Temp\ipykernel_22084\3529175983.py:46: UserWarning: Using torch.cross without specifying the dim arg is deprecated.
Please either pass the dim explicitly or simply use torch.linalg.cross.
The default value of dim will change to agree with that of linalg.cross in a future release. (Triggered internally at C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\Cross.cpp:67.)
  print(torch.cross(v2, v1)) # z축 단위 벡터의 음수값 (v1 x v2 == -v2 x v1)


In [17]:
a = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
print('a:')
print(a)
print(torch.sin(a))   # 이 연산은 메모리에 새로운 tensor를 생성합니다.
print(a)              # a는 변하지 않습니다.

b = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
print('\nb:')
print(b)
print(torch.sin_(b))  # 밑줄에 주목하세요.
print(b)              # b가 변합니다.

a:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 2.3562])

b:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7071, 1.0000, 0.7071])


In [18]:
a = torch.ones(2, 2)
b = torch.rand(2, 2)

print('Before:')
print(a)
print(b)
print('\nAfter adding:')
print(a.add_(b))
print(a)
print(b)
print('\nAfter multiplying')
print(b.mul_(b))
print(b)

Before:
tensor([[1., 1.],
        [1., 1.]])
tensor([[0.3788, 0.4567],
        [0.0649, 0.6677]])

After adding:
tensor([[1.3788, 1.4567],
        [1.0649, 1.6677]])
tensor([[1.3788, 1.4567],
        [1.0649, 1.6677]])
tensor([[0.3788, 0.4567],
        [0.0649, 0.6677]])

After multiplying
tensor([[0.1435, 0.2086],
        [0.0042, 0.4459]])
tensor([[0.1435, 0.2086],
        [0.0042, 0.4459]])


In [19]:
a = torch.ones(2, 2)
b = torch.rand(2, 2)

print('Before:')
print(a)
print(b)
print('\nAfter adding:')
print(a.add_(b))
print(a)
print(b)
print('\nAfter multiplying')
print(b.mul_(b))
print(b)

Before:
tensor([[1., 1.],
        [1., 1.]])
tensor([[0.7826, 0.1332],
        [0.0023, 0.4945]])

After adding:
tensor([[1.7826, 1.1332],
        [1.0023, 1.4945]])
tensor([[1.7826, 1.1332],
        [1.0023, 1.4945]])
tensor([[0.7826, 0.1332],
        [0.0023, 0.4945]])

After multiplying
tensor([[6.1248e-01, 1.7732e-02],
        [5.1415e-06, 2.4454e-01]])
tensor([[6.1248e-01, 1.7732e-02],
        [5.1415e-06, 2.4454e-01]])


In [20]:
a = torch.rand(2, 2)
b = torch.rand(2, 2)
c = torch.zeros(2, 2)
old_id = id(c)

print(c)
d = torch.matmul(a, b, out=c)
print(c)                # c의 값이 변경되었습니다.


# assert 문은 파이썬의 디버깅 목적으로 사용된ㄴ 도구
# assert condition, message : condition에 부합하지 않으면 AssertionError 발생
assert c is d           # c와 d가 서로 단순히 같은 값을 가지는지가 아니라 같은 객체인지 테스트합니다.
assert id(c) == old_id  # 새로운 c는 이전 객체와 확실히 같은 객체입니다.

torch.rand(2, 2, out=c) # 다시 한번 생성해봅시다!
print(c)                # c의 값이 다시 바뀌었습니다.
assert id(c) == old_id  # 하지만 여전히 같은 객체네요!

tensor([[0., 0.],
        [0., 0.]])
tensor([[1.0062, 0.1893],
        [0.7523, 0.2162]])
tensor([[0.0905, 0.4485],
        [0.8740, 0.2526]])


## Tensor를 복사하기

변수에 텐서를 할당하는 것은변수가 tensor의 라벨이 되고 값을 복사하지 않음.

In [21]:
a = torch.ones(2, 2)
b = a

a[0][1] = 561  # a의 값을 바꾸면...
print(b)       # ...b의 값이 바뀝니다.

tensor([[  1., 561.],
        [  1.,   1.]])


In [23]:
# clone 메소드
a = torch.ones(2, 2)
b = a.clone()

assert b is not a      # 메모리 상의 다른 객체입니다...
print(torch.eq(a, b))  # ...하지만 여전히 같은 값을 가지고 있네요!

a[0][1] = 561          # a가 변경되었습니다...
print(b)               # ...하지만 여전히 b는 이전 값을 가지고 있네요.

tensor([[True, True],
        [True, True]])
tensor([[1., 1.],
        [1., 1.]])


clone() 메소드를 사용할 때 소스텐서가 autograd를 가지면 clone이 가능하다. 
만약 모델이 그 모델의 forward() 메소드에 여러갈래의 계산 경로가 있고, 원본 텐서와 그것의 복제본 모두가 모델의 출력에 기여한다면, 두 텐서에 대한 autograd를 설정하는 모델 학습을 활성화한다.
그리고 원본 텐서나 복제본 모두 변화도를 추저갈 필요가 없을 때 소스텐서의 autograd가 꺼져있다면 clone을 사용할 수 있다. 

세번째 경우, 변화도가 모든 것을 위해 켜져 있지만 일부 지표를 생성하기 위해서 스트림 중간에서 일부 값을 생성하고 싶어하는 모델의 forward() 함수에서 계산을 수행한다고 상상해보았을 때, source tensor에 .detach()메소드를 사용할 수 있다.

In [24]:
a = torch.rand(2, 2, requires_grad=True) # autograd와 계산 히스토리 추적기능을 켠다.
print(a)

tensor([[0.6923, 0.7545],
        [0.7746, 0.2330]], requires_grad=True)


In [25]:
b = a.clone() # a를 복제하고 b라고 라벨을 붙임. b를 출력할 때 계산 히스토리가 추적되고 있음을 확인.
print(b)

tensor([[0.6923, 0.7545],
        [0.7746, 0.2330]], grad_fn=<CloneBackward0>)


In [26]:
c = a.detach().clone()
print(c) # c에 계산 히스토리가 없음, requires_grad=True 옵션이 없음.

print(a)

tensor([[0.6923, 0.7545],
        [0.7746, 0.2330]])
tensor([[0.6923, 0.7545],
        [0.7746, 0.2330]], requires_grad=True)


## GPU 환경으로 이동하기

Pytorch의 주된 장점은 CUDA가 호환되는 Nvidia GPU에서의 강력한 성능 가속화이다.

In [28]:
if torch.cuda.is_available():
    print('We have a Gpu!')
else:
    print('CPU only')

We have a Gpu!


데이터를 GPU가 확인할 수 있는 어떤 공간에 저장해야 한다. CPU는 컴퓨터의 RAM에서 데이터를 이용해서 계산을 수행한다.

GPU는 전용 메모리가 연결되어 있는데, GPU에서 계산을 수행하고 싶을 때마다 계산에 필요한 모든 데이터를 GPU장치가 접근 가능한 메모리로 이동해야 한다.

'GPU가 접근 가능한 메모리로 데이터를 이동한다' == '데이터를 GPU로 옮긴다'

In [29]:
if torch.cuda.is_available():
    gpu_rand = torch.rand(2, 2, device='cuda')
    print(gpu_rand)

else:
    print('sorry cpu only')

tensor([[0.3344, 0.2640],
        [0.2119, 0.0582]], device='cuda:0')


기본적으로 새로운 텐서는 CPU에 생성되므로, 텐서를 GPU에 생성하고 싶을 때 device 인자를 반드시 명시해주어야한다. 
새로운 텐서를 출력할 때, 파이토치는 어느 장치에 객체가 있는지 알려준다.

* torch.cuda.device_count()를 사용해서 GPU 개수를 조회함
* device='cuda:0', device='cuda:1'

장치 이름을 문자열 상수로 지정하는 것은 유지보수에 취약함.
문자열 대신에 텐서를 저장할 장치 핸들러를 생성하는 것으로 유지 보수가 쉬운 코드를 작성할 수 있음.

In [30]:
if torch.cuda.is_available():
    my_device=torch.device('cuda')
else:
    my_device=torch.device('cpu')
print('Device : {}'.format(my_device))

x = torch.rand(2, 2, device=my_device)
print(x)

Device : cuda
tensor([[0.0024, 0.6778],
        [0.2441, 0.6812]], device='cuda:0')


In [31]:
# 한 장치에 텐서가 있을 때, to() 메소드를 사용해서 다른 장치로 이동할 수 있음.
# cpu에 텐서를 생성하고, 이전 셀에서 얻은 장치 핸들러로 텐서를 이동시킴

y = torch.rand(2, 2)
y = y.to(my_device)

In [33]:
# !! 2개 이상의 텐서를 포함한 계산을 하기 위해서는 모든 텐서가 같은 장치에 있어야함.
# runtime error

x = torch.rand(2, 2)
y = torch.rand(2, 2, deivce='gpu')

TypeError: rand() received an invalid combination of arguments - got (int, int, deivce=str), but expected one of:
 * (tuple of ints size, *, torch.Generator generator, tuple of names names, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, torch.Generator generator, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, tuple of names names, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)


## Tensor의 shape 다루기

### 차원의 개수 변경하기
모델의 입력에 단일 인스턴스를 전달할 때, 차원의개수를 변경할 필요가 있다. 파이토치에서 일반적으로 입력에 배치가 들어온다.

ex. 3개의 색깔 채널을 가진 226x226 image

이미지를 불러오고 텐서로 변환하면 (3, 226, 226) shape을 가진 텐서가 됨. --> (N, 3, 226, 226)


In [35]:
a = torch.rand(3, 226, 226)
b = a.unsqueeze(0)

# unsqueeze() 메소드는 크기가 1인 차원을 추가
# unsqueeze(0)은 새로운 0번째 차원을 추가

print(a.shape)
print(b.shape)

torch.Size([3, 226, 226])
torch.Size([1, 3, 226, 226])


In [36]:
c = torch.rand(1, 1, 1, 1, 1)
# 차원을 하나 확장해도 텐서에 있는 원소의 개수는 변하지 않는다.
print(c)

tensor([[[[[0.7112]]]]])


ex. 각 입력값에 대한 모델의 출력값이 20개의 원소를 가진 vector
* N : 입력 배치에 있는 인스턴스의 개수
* 출력  (N, 20)

배치 shape이 아닌 연산 결과를 얻고싶다면??


In [37]:
a = torch.rand(1, 20)
print(a.shape)
print(a)

torch.Size([1, 20])
tensor([[0.8203, 0.3941, 0.7000, 0.6464, 0.6506, 0.7114, 0.1617, 0.5450, 0.5948,
         0.4542, 0.0465, 0.7545, 0.7612, 0.3475, 0.2052, 0.6022, 0.1849, 0.2320,
         0.0269, 0.2416]])


In [40]:
b= a.squeeze(0)
print(b.shape)
print(b)

torch.Size([20])
tensor([0.8203, 0.3941, 0.7000, 0.6464, 0.6506, 0.7114, 0.1617, 0.5450, 0.5948,
        0.4542, 0.0465, 0.7545, 0.7612, 0.3475, 0.2052, 0.6022, 0.1849, 0.2320,
        0.0269, 0.2416])


In [41]:
c = torch.rand(2, 2)
print(c.shape)

torch.Size([2, 2])


In [42]:
d= c.squeeze(0) # 차원의 값이 1이 아니므로 squeeze가 작동하지 않음.
print(d.shape)

torch.Size([2, 2])


오직 차원의 값이 1인 경우에만 squeeze()를 사용할 수 있다. 이 경우가 아니면 텐서의 원소 개수가 바뀌기 때문이다.

unsqueeze는 broadcasting을 쉽게 하는 경우에도 사용된다. 

In [43]:
a = torch.ones(4, 3, 2)

c = a * torch.rand(  3, 1)
print(c)

tensor([[[0.0164, 0.0164],
         [0.5220, 0.5220],
         [0.5693, 0.5693]],

        [[0.0164, 0.0164],
         [0.5220, 0.5220],
         [0.5693, 0.5693]],

        [[0.0164, 0.0164],
         [0.5220, 0.5220],
         [0.5693, 0.5693]],

        [[0.0164, 0.0164],
         [0.5220, 0.5220],
         [0.5693, 0.5693]]])


In [44]:
a = torch.ones(4, 3, 2)
b = torch.rand(   3)     # a * b를 시도하는 것은 runtime error가 발생합니다.
c = b.unsqueeze(1)       # 끝에 새로운 차원을 추가해서 2차원 tensor로 바꿉니다.
print(c.shape)
print(a * c)             # broadcasting이 다시 작동합니다!

torch.Size([3, 1])
tensor([[[0.6086, 0.6086],
         [0.5455, 0.5455],
         [0.0417, 0.0417]],

        [[0.6086, 0.6086],
         [0.5455, 0.5455],
         [0.0417, 0.0417]],

        [[0.6086, 0.6086],
         [0.5455, 0.5455],
         [0.0417, 0.0417]],

        [[0.6086, 0.6086],
         [0.5455, 0.5455],
         [0.0417, 0.0417]]])


In [45]:
batch_me = torch.rand(3, 226, 226)
print(batch_me.shape)
batch_me.unsqueeze_(0)
print(batch_me.shape)

torch.Size([3, 226, 226])
torch.Size([1, 3, 226, 226])


원소의 개수와 원소의 값은 여전히 유지하면서 텐서의 shape을 한번에 바꾸고 싶을 때가 있다. 모델의 conv layer와 linear layer 사이 인터페이스.

conv layer는 특성의 수 x 너비 x 높이 shape의 텐서를 출ㄹ격을 생성

linear layer는 입력값으로 1차원을 받음.

reshape

In [46]:
output3d = torch.rand(6, 20, 20)
print(output3d.shape)

torch.Size([6, 20, 20])


In [47]:
input1d = output3d.reshape(6*20*20)
print(input1d.shape)

torch.Size([2400])


In [49]:
print(torch.reshape(output3d, (6*20*20,)).shape) # (6*20*20,)는 텐서 쉐입을 나타낼 때 튜플을 기대하므로 이 인자가 진짜 1개 원소를 가진 튜플이라고 하기 위해 컴마 추가

torch.Size([2400])


텐서를 바라보는 관점. 메모리의 같은 지역을 바라보는 서로 다른 관점을 가진 텐서 객체

소스텐서에 어떠한 변화가 있으면 해당 텐서를 바라보고 있는 다른 객체 또한 값이 변한다.

### Numpy로 변환

NumPy의 ndarrays에 저장되어있는 데이터를 사용하는 코드를 가지고 있다면, 같은 데이터를 파이토치의 GPU가속을 사용할수 있고 파이토치 텐서로 표현할 수 있다.
ndarray와 파이토치끼리 바꿀 수 있다. 

In [50]:
import numpy as np

numpy_array = np.ones((2, 3))
print(numpy_array)

[[1. 1. 1.]
 [1. 1. 1.]]


In [51]:
pytorch_tensor = torch.from_numpy(numpy_array)
print(pytorch_tensor)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [52]:
pytorch_rand = torch.rand(2, 3)
print(pytorch_rand)

numpy_rand = pytorch_rand.numpy()
print(numpy_rand)

tensor([[0.2926, 0.6360, 0.9112],
        [0.9312, 0.3967, 0.2918]])
[[0.2925921  0.63602173 0.9111862 ]
 [0.93117917 0.39667493 0.2918461 ]]


In [53]:
# 변환된 객체들을 해당 객체의 소스객체가 위치한 메모리의 같은 공간을 사용한다.
# 즉 한 객체가 변하면 다른 것에 영향을 준다.

numpy_array[1, 1] = 23
print(pytorch_tensor)

pytorch_rand[1, 1] = 17
print(numpy_rand)

tensor([[ 1.,  1.,  1.],
        [ 1., 23.,  1.]], dtype=torch.float64)
[[ 0.2925921   0.63602173  0.9111862 ]
 [ 0.93117917 17.          0.2918461 ]]
